// File generated by scripts/extract-objects.py
// DO NOT EDIT!

#ifndef _CHESTS_OBJECTS_H
#define _CHESTS_OBJECTS_H

#include <types.h>

external const UINT8 CHESTS[];
#define CHESTS_COUNT 6;

#endif
