// File generated by scripts/extract-objects.py
// DO NOT EDIT!

#include <types.h>

const UINT8 CHESTS[] = {
    // x, y, object_id
     60,  64,   5,  // Sword
     38,  46,   4,  // Seamless scrolling
     42,  36,   3,  // Sound effects
     24,  42,   2,  // Scrolling
     20,  46,   1,  // 2D moves
     30,  46,   0,  // D-PAD Left key
};
