// This file was generated by img2gb, DO NOT EDIT

#ifndef _EVOLAND_LOGO_TILESET_H
#define _EVOLAND_LOGO_TILESET_H

extern const UINT8 EVOLAND_LOGO_TILESET[];
#define EVOLAND_LOGO_TILESET_TILE_COUNT 88


#endif
