// This file was generated by img2gb, DO NOT EDIT

#ifndef _BACKGROUND_TILEMAP_H
#define _BACKGROUND_TILEMAP_H

extern const UINT8 BG_TILEMAP[];
#define BG_TILEMAP_WIDTH 140
#define BG_TILEMAP_HEIGHT 80


#endif
